<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/2024_06_04_lr_get_data_ready.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/Annepikson/HypatiaAcademy/master/ml/Top_200_Movies_Dataset_2023(Cleaned).csv")
df


# we want to make a prediction,  we a model that give some inputs x1, x2, x3, ...  we can predict y

# Warner bros movies are highly ranked

# ranking is related to gross sales


#y=rank

#x1=total gross

#x=distributor

,Rank,Title,Theaters,Total Gross,Release Date,Distributor
0,1,Barbie,"4,337","$594,254,460",2023-07-21 00:00:00,Warner Bros.
1,2,The Super Mario Bros. Movie,"4,371","$574,759,600",2023-04-05 00:00:00,Universal Pictures
2,3,Spider-Man: Across the Spider-Verse,"4,332","$381,178,195",2023-06-02 00:00:00,Columbia Pictures
3,4,Guardians of the Galaxy Vol. 3,"4,450","$358,995,815",2023-05-05 00:00:00,Walt Disney Studios Motion Pictures
4,5,Oppenheimer,"3,761","$300,144,670",2023-07-21 00:00:00,Universal Pictures
...,...,...,...,...,...,...
195,196,Contempt4k Restoration - 60th Anniversary,8,"$173,816",2023-06-30 00:00:00,Rialto Pictures
196,197,The Wrath of Becky,274,"$168,109",2023-05-26 00:00:00,Quiver Distribution
197,198,The Starling Girl,114,"$161,290",2023-05-12 00:00:00,Bleecker Street Media
198,199,¡Que viva México!,90,"$161,222",2023-03-24 00:00:00,Sony Pictures Entertainment (SPE)
199,200,Enys Men,62,"$189,579",2023-03-31 00:00:00,'-

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          200 non-null    int64
 1   Title         200 non-null    object
 2   Theaters      200 non-null    object
 3   Total Gross   200 non-null    object
 4   Release Date  200 non-null    object
 5   Distributor   200 non-null    object
dtypes: int64(1), object(5)
memory usage: 9.5+ KB

In [9]:



import re

a = "$594,254,460"

#s=re.sub(r'[\d\.]+', '', a)

s=a.replace('$', '')
t=s.replace(',', '')
int(t)

594254460

In [11]:
import re


def tonumber(n):

  s=n.replace('$', '')
  t=s.replace(',', '')
  return int(t)

In [12]:
tonumber("$555,222,111")

555222111

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x2=le.fit_transform(df['Distributor'])

x2

array([49, 44, 10, 48, 44, 48,  1, 48, 20,  3, 48, 28, 28, 43, 48, 44, 44,
       28, 49, 28, 44, 28, 34, 49, 49, 44, 10, 48, 49,  0, 20, 40, 49, 48,
        2, 28, 44, 40, 20, 40, 14, 49, 20, 34, 40, 20, 14, 51, 48, 44, 23,
       44, 14, 12, 28, 44, 20,  2, 20,  3, 11,  2, 40, 42, 11, 49,  2,  2,
       20,  0, 20, 41, 28, 34, 44, 13, 38, 40, 43, 24,  2, 25, 18, 25, 47,
       49, 33,  0, 13, 35, 13, 48,  5, 50, 14, 44, 36, 39, 35,  7, 51, 13,
       43, 33, 40, 17, 44,  5, 33,  5, 13, 16,  8, 11, 35, 14, 24, 17, 13,
        0, 46, 41, 15, 14, 17, 13, 48,  2,  5,  0, 24,  2,  9, 14, 33, 17,
       39, 50,  0, 13,  0, 47, 40, 10, 22, 39, 17, 37, 13, 13, 13, 14,  7,
        2, 17,  0, 26, 24, 39, 13, 39,  4,  6, 27, 30,  0,  0, 40, 29,  0,
        0,  0, 11,  0, 13, 27, 21,  0,  6, 33, 45, 14, 35, 50, 45,  0,  0,
       24, 37, 40, 13,  2,  0, 40, 19, 32, 31,  5, 40,  0])

In [31]:

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from pylab import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [18]:
y=df['Rank'].values

numpy.ndarray

In [21]:
x1=df['Total Gross'].apply(tonumber)

In [27]:
# use capital letters when dealing arrays that has more than one dimension
import numpy as np

X=np.column_stack((x1,x2))
X

array([[594254460,        49],
       [574759600,        44],
       [381178195,        10],
       [358995815,        48],
       [300144670,        44],
       [297895447,        48],
       [684075767,         1],
       [214504909,        48],
       [187131806,        20],
       [180587629,         3],
       [174116627,        48],
       [168248955,        28],
       [157066392,        28],
       [156248615,        43],
       [151692473,        48],
       [145960660,        44],
       [185535345,        44],
       [108161389,        28],
       [108133313,        49],
       [ 99847538,        28],
       [ 95043350,        44],
       [ 93277026,        28],
       [ 82042800,        34],
       [ 74469810,        49],
       [ 67233054,        49],
       [ 64388510,        44],
       [ 64267657,        10],
       [ 62291150,        48],
       [ 57638006,        49],
       [ 52460106,         0],
       [ 52102987,        20],
       [ 50452282,        40],
       [ 46566539,        49],
       [ 43244282,        48],
       [ 41066389,         2],
       [ 39330588,        28],
       [ 35397980,        44],
       [ 32502025,        40],
       [ 32111181,        20],
       [ 32062904,        40],
       [ 28049165,        14],
       [ 26005156,        49],
       [ 20372406,        20],
       [ 20009380,        34],
       [ 18541753,        40],
       [ 17707207,        20],
       [ 17556340,        14],
       [ 17487476,        51],
       [453829060,        48],
       [ 17152625,        44],
       [ 16938039,        23],
       [ 16840900,        44],
       [ 16271910,        14],
       [ 15753600,        12],
       [ 15033795,        28],
       [ 13309285,        44],
       [ 12897789,        20],
       [ 17463630,         2],
       [ 12089391,        20],
       [ 12084084,         3],
       [ 10760901,        11],
       [ 10724951,         2],
       [ 10458331,        40],
       [ 23708080,        42],
       [ 10117806,        11],
       [  9002247,        49],
       [ 77191785,         2],
       [  8176562,         2],
       [  7265622,        20],
       [  7259924,         0],
       [  6496125,        20],
       [  8093270,        41],
       [ 15351455,        28],
       [  6230837,        34],
       [ 17348945,        44],
       [  5525069,        13],
       [  5433685,        38],
       [  5426772,        40],
       [  5456531,        43],
       [  5078400,        24],
       [  4830788,         2],
       [  4813132,        25],
       [  4500169,        18],
       [  4350243,        25],
       [  4303645,        47],
       [  4275970,        49],
       [  3821285,        33],
       [  3813000,         0],
       [  3649422,        13],
       [  3644801,        35],
       [  3574915,        13],
       [  3541159,        48],
       [  3496761,         5],
       [  5023132,        50],
       [  3400020,        14],
       [ 50057405,        44],
       [  3025631,        36],
       [  3038113,        39],
       [ 38501125,        35],
       [  2515612,         7],
       [  2503604,        51],
       [  2500574,        13],
       [  2210465,        43],
       [  2136832,        33],
       [  2104152,        40],
       [  2052272,        17],
       [  1864240,        44],
       [  1856809,         5],
       [  1802442,        33],
       [  1775876,         5],
       [  1750639,        13],
       [  2090261,        16],
       [  1721446,         8],
       [  1588491,        11],
       [ 10582266,        35],
       [  1545600,        14],
       [  1500014,        24],
       [  1476597,        17],
       [  1455081,        13],
       [  1443314,         0],
       [  1293722,        46],
       [  1290000,        41],
       [  1256517,        15],
       [  6773650,        14],
       [  1188032,        17],
       [  1176085,        13],
       [ 37968963,        48],
       [  1100113,         2],
       [  1097067,         5],
       [  1090155,         0],
       [  1046899,        24],
       [   754483,         2],
       [   909411,         9],
       [   897190,        14],
       [   855173,        33],
       [   811739,        17],
       [   798774,        39],
       [   803189,        50],
       [   765218,         0],
       [   757981,        13],
       [   750010,         0],
       [   744169,        47],
       [   705355,        40],
       [ 20511938,        10],
       [   667114,        22],
       [   653780,        39],
       [   705767,        17],
       [  1068782,        37],
       [   601490,        13],
       [   577004,        13],
       [   567448,        13],
       [   556585,        14],
       [   541633,         7],
       [  1658790,         2],
       [   538551,        17],
       [   535202,         0],
       [   533978,        26],
       [  4608096,        24],
       [   451549,        39],
       [   447912,        13],
       [   449650,        39],
       [   412550,         4],
       [   379890,         6],
       [   327584,        27],
       [   340017,        30],
       [   339946,         0],
       [   335775,         0],
       [   335417,        40],
       [   326184,        29],
       [   325583,         0],
       [   320000,         0],
       [   310746,         0],
       [   309757,        11],
       [   308825,         0],
       [   295539,        13],
       [   302550,        27],
       [   415827,        21],
       [   293496,         0],
       [   288414,         6],
       [   276672,        33],
       [   302456,        45],
       [   273860,        14],
       [  1177577,        35],
       [   277011,        50],
       [   256566,        45],
       [   221738,         0],
       [   500082,         0],
       [   213953,        24],
       [   204620,        37],
       [   214470,        40],
       [   197702,        13],
       [   196920,         2],
       [   193829,         0],
       [ 46888441,        40],
       [   180135,        19],
       [   173816,        32],
       [   168109,        31],
       [   161290,         5],
       [   161222,        40],
       [   189579,         0]])

In [28]:
X.shape

(200, 2)

In [29]:
y.shape

(200,)

In [39]:
X

array([[594254460,        49],
       [574759600,        44],
       [381178195,        10],
       [358995815,        48],
       [300144670,        44],
       [297895447,        48],
       [684075767,         1],
       [214504909,        48],
       [187131806,        20],
       [180587629,         3],
       [174116627,        48],
       [168248955,        28],
       [157066392,        28],
       [156248615,        43],
       [151692473,        48],
       [145960660,        44],
       [185535345,        44],
       [108161389,        28],
       [108133313,        49],
       [ 99847538,        28],
       [ 95043350,        44],
       [ 93277026,        28],
       [ 82042800,        34],
       [ 74469810,        49],
       [ 67233054,        49],
       [ 64388510,        44],
       [ 64267657,        10],
       [ 62291150,        48],
       [ 57638006,        49],
       [ 52460106,         0],
       [ 52102987,        20],
       [ 50452282,        40],
       [ 46566539,        49],
       [ 43244282,        48],
       [ 41066389,         2],
       [ 39330588,        28],
       [ 35397980,        44],
       [ 32502025,        40],
       [ 32111181,        20],
       [ 32062904,        40],
       [ 28049165,        14],
       [ 26005156,        49],
       [ 20372406,        20],
       [ 20009380,        34],
       [ 18541753,        40],
       [ 17707207,        20],
       [ 17556340,        14],
       [ 17487476,        51],
       [453829060,        48],
       [ 17152625,        44],
       [ 16938039,        23],
       [ 16840900,        44],
       [ 16271910,        14],
       [ 15753600,        12],
       [ 15033795,        28],
       [ 13309285,        44],
       [ 12897789,        20],
       [ 17463630,         2],
       [ 12089391,        20],
       [ 12084084,         3],
       [ 10760901,        11],
       [ 10724951,         2],
       [ 10458331,        40],
       [ 23708080,        42],
       [ 10117806,        11],
       [  9002247,        49],
       [ 77191785,         2],
       [  8176562,         2],
       [  7265622,        20],
       [  7259924,         0],
       [  6496125,        20],
       [  8093270,        41],
       [ 15351455,        28],
       [  6230837,        34],
       [ 17348945,        44],
       [  5525069,        13],
       [  5433685,        38],
       [  5426772,        40],
       [  5456531,        43],
       [  5078400,        24],
       [  4830788,         2],
       [  4813132,        25],
       [  4500169,        18],
       [  4350243,        25],
       [  4303645,        47],
       [  4275970,        49],
       [  3821285,        33],
       [  3813000,         0],
       [  3649422,        13],
       [  3644801,        35],
       [  3574915,        13],
       [  3541159,        48],
       [  3496761,         5],
       [  5023132,        50],
       [  3400020,        14],
       [ 50057405,        44],
       [  3025631,        36],
       [  3038113,        39],
       [ 38501125,        35],
       [  2515612,         7],
       [  2503604,        51],
       [  2500574,        13],
       [  2210465,        43],
       [  2136832,        33],
       [  2104152,        40],
       [  2052272,        17],
       [  1864240,        44],
       [  1856809,         5],
       [  1802442,        33],
       [  1775876,         5],
       [  1750639,        13],
       [  2090261,        16],
       [  1721446,         8],
       [  1588491,        11],
       [ 10582266,        35],
       [  1545600,        14],
       [  1500014,        24],
       [  1476597,        17],
       [  1455081,        13],
       [  1443314,         0],
       [  1293722,        46],
       [  1290000,        41],
       [  1256517,        15],
       [  6773650,        14],
       [  1188032,        17],
       [  1176085,        13],
       [ 37968963,        48],
       [  1100113,         2],
       [  1097067,         5],
       [  1090155,         0],
       [  1046899,        24],
       [   754483,         2],
       [   909411,         9],
       [   897190,        14],
       [   855173,        33],
       [   811739,        17],
       [   798774,        39],
       [   803189,        50],
       [   765218,         0],
       [   757981,        13],
       [   750010,         0],
       [   744169,        47],
       [   705355,        40],
       [ 20511938,        10],
       [   667114,        22],
       [   653780,        39],
       [   705767,        17],
       [  1068782,        37],
       [   601490,        13],
       [   577004,        13],
       [   567448,        13],
       [   556585,        14],
       [   541633,         7],
       [  1658790,         2],
       [   538551,        17],
       [   535202,         0],
       [   533978,        26],
       [  4608096,        24],
       [   451549,        39],
       [   447912,        13],
       [   449650,        39],
       [   412550,         4],
       [   379890,         6],
       [   327584,        27],
       [   340017,        30],
       [   339946,         0],
       [   335775,         0],
       [   335417,        40],
       [   326184,        29],
       [   325583,         0],
       [   320000,         0],
       [   310746,         0],
       [   309757,        11],
       [   308825,         0],
       [   295539,        13],
       [   302550,        27],
       [   415827,        21],
       [   293496,         0],
       [   288414,         6],
       [   276672,        33],
       [   302456,        45],
       [   273860,        14],
       [  1177577,        35],
       [   277011,        50],
       [   256566,        45],
       [   221738,         0],
       [   500082,         0],
       [   213953,        24],
       [   204620,        37],
       [   214470,        40],
       [   197702,        13],
       [   196920,         2],
       [   193829,         0],
       [ 46888441,        40],
       [   180135,        19],
       [   173816,        32],
       [   168109,        31],
       [   161290,         5],
       [   161222,        40],
       [   189579,         0]])

In [40]:
y

-76.77361344617856

In [32]:
reg = LinearRegression()
reg.fit(X, y)

LinearRegression()

In [33]:
np.set_printoptions(suppress=True, precision=10)

print('Coefficients: \n', reg.coef_)
print('\n Intercept: \n', reg.intercept_)

Coefficients:
 [-0.0000002863 -0.7538366995]

 Intercept:
 130.29943672732145

In [34]:
#. y = m1x1 + m2x2 + b

x1, x2 = [594254460,        49]


# so our linear regression model said that the movie rank (y) can be approximated by this formula

# m1 = -0.0000002863
# m2 = -0.7538366995

# for every x1 and every x2

y = -0.0000002863 * x1 -0.7538366995 * x2 + 130.29943672732145

In [35]:
y

-76.77361344617856

# to test this we would do a lot


now we have our model.  we have to ask:  is it correct?  is it logical?

draw a chart

R-score

# Homework

Our hypothese is that life expectancy (how long will you live) is
corelated with

* y =

* Alcohol make that me x1

* life expectancy

* x2 = Diphtheria

* x3 = under-five deaths

* x4 = percentage expenditure

* x5 = Status (use labeleconder)


```
'Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling']
  ```

In [37]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/werowe/HypatiaAcademy/master/ml/Life%20Expectancy%20Data.csv")

df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [38]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')