<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/stats/20-year-Paphosweather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from datetime import date
from datetime import datetime,date
import time
import pandas as pd
import numpy as np
import statistics as st
from dateutil import parser

In [38]:
def toDate(epoch_time):
    return datetime.fromtimestamp(epoch_time)

In [3]:
df=pd.read_json('https://raw.githubusercontent.com/werowe/HypatiaAcademy/master/assignments/paphosWeather2023.json',lines=True)

In [8]:
df=df.T

In [33]:
df = pd.json_normalize(df[0])

In [34]:
df.columns

Index(['dt', 'dt_iso', 'timezone', 'weather', 'lat', 'city_name', 'lon',
       'main.temp', 'main.temp_min', 'main.temp_max', 'main.feels_like',
       'main.pressure', 'main.humidity', 'main.dew_point', 'clouds.all',
       'wind.speed', 'wind.deg', 'rain.1h', 'wind.gust'],
      dtype='object')

In [51]:
# Function to clean and convert the timestamp strings
def clean_timestamp(timestamp):
    # Remove the " UTC" part and convert to datetime
    cleaned_timestamp = timestamp.replace(" UTC", "")
    return pd.to_datetime(cleaned_timestamp)

# Apply the function to the Timestamp column
df['dt_iso'] = df['dt_iso'].apply(clean_timestamp)

In [52]:
df['datetime'] = pd.to_datetime(df['dt_iso'])

In [54]:
df.set_index('datetime', inplace=True)

In [67]:
last=df.loc[df.index.year==2023 & df.index.month.isin([6, 7, 8])]

In [61]:
last

,dt,dt_iso,timezone,weather,lat,city_name,lon,main.temp,main.temp_min,main.temp_max,main.feels_like,main.pressure,main.humidity,main.dew_point,clouds.all,wind.speed,wind.deg,rain.1h,wind.gust
datetime,,,,,,,,,,,,,,,,,,,
2023-01-01 00:00:00+00:00,1672531200,2023-01-01 00:00:00+00:00,7200,"[{'id': 801, 'main': 'Clouds', 'description': ...",34.775395,Paphos,32.421779,13.76,9.43,16.60,12.68,1027,57,5.40,20,2.60,20,NaN,0.0
2023-01-01 01:00:00+00:00,1672534800,2023-01-01 01:00:00+00:00,7200,"[{'id': 800, 'main': 'Clear', 'description': '...",34.775395,Paphos,32.421779,13.59,8.60,16.54,12.60,1026,61,6.22,0,1.54,0,NaN,NaN
2023-01-01 02:00:00+00:00,1672538400,2023-01-01 02:00:00+00:00,7200,"[{'id': 800, 'main': 'Clear', 'description': '...",34.775395,Paphos,32.421779,13.63,8.60,16.47,12.77,1026,66,7.40,0,2.60,70,NaN,0.0
2023-01-01 03:00:00+00:00,1672542000,2023-01-01 03:00:00+00:00,7200,"[{'id': 801, 'main': 'Clouds', 'description': ...",34.775395,Paphos,32.421779,13.48,8.60,16.41,12.61,1026,66,7.26,20,3.10,70,NaN,0.0
2023-01-01 04:00:00+00:00,1672545600,2023-01-01 04:00:00+00:00,7200,"[{'id': 801, 'main': 'Clouds', 'description': ...",34.775395,Paphos,32.421779,13.72,9.60,16.35,12.77,1026,62,6.58,20,3.10,20,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-01 19:00:00+00:00,1688238000,2023-07-01 19:00:00+00:00,10800,"[{'id': 800, 'main': 'Clear', 'description': '...",34.775395,Paphos,32.421779,24.83,23.18,25.83,25.48,1007,81,21.35,0,3.09,310,NaN,NaN
2023-07-01 20:00:00+00:00,1688241600,2023-07-01 20:00:00+00:00,10800,"[{'id': 800, 'main': 'Clear', 'description': '...",34.775395,Paphos,32.421779,24.68,24.19,25.33,25.37,1007,83,21.60,0,3.09,320,NaN,NaN
2023-07-01 21:00:00+00:00,1688245200,2023-07-01 21:00:00+00:00,10800,"[{'id': 801, 'main': 'Clouds', 'description': ...",34.775395,Paphos,32.421779,24.42,23.60,24.97,25.22,1007,88,22.30,20,2.06,330,NaN,NaN
2023-07-01 22:00:00+00:00,1688248800,2023-07-01 22:00:00+00:00,10800,"[{'id': 800, 'main': 'Clear', 'description': '...",34.775395,Paphos,32.421779,23.74,21.52,24.26,24.47,1007,88,21.63,7,2.06,20,NaN,NaN
2023-07-01 23:00:00+00:00,1688252400,2023-07-01 23:00:00+00:00,10800,"[{'id': 800, 'main': 'Clear', 'description': '...",34.775395,Paphos,32.421779,23.47,20.96,24.22,24.20,1007,89,21.55,10,3.09,20,NaN,NaN