<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/pandas/ilya-pandas_homework_20_02_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [45]:
# I found the dataset with the list of computer games that are on steam
df = pd.read_csv('https://raw.githubusercontent.com/illiazhupanov/pandas/refs/heads/main/steam_games.csv')
df

,steam_appid,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,...,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
0,2719580,勇者の伝説の勇者,['ぽけそう'],['ぽけそう'],"['Single-player', 'Family Sharing']","['Casual', 'Indie']",0,0,['windows'],True,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.99
1,2719590,Light No Fire,['Hello Games'],['Hello Games'],"['Single-player', 'Multi-player', 'Co-op', 'On...","['Action', 'Adventure']",0,0,['windows'],False,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.00
2,2719600,Lorhaven: Cursed War,['GoldenGod Games'],['GoldenGod Games'],"['Single-player', 'Multi-player', 'PvP', 'Shar...","['RPG', 'Strategy']",0,32,"['windows', 'mac']",True,...,[],9,8,1,0.0,9 user reviews,88.9,0,False,9.99
3,2719610,PUIQ: Demons,['Giammnn'],['Giammnn'],"['Single-player', 'Steam Achievements', 'Famil...","['Action', 'Casual', 'Indie', 'RPG']",0,28,['windows'],True,...,[],0,0,0,0.0,No user reviews,0.0,0,False,2.99
4,2719650,Project XSTING,['Saucy Melon'],['Saucy Melon'],"['Single-player', 'Steam Achievements', 'Steam...","['Action', 'Casual', 'Indie', 'Early Access']",0,42,['windows'],True,...,[],9,9,0,0.0,9 user reviews,100.0,0,False,7.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71424,2294300,Touchdown Pinball,['Super PowerUp Games'],['Super PowerUp Games'],"['Single-player', 'Steam Achievements', 'Full ...",['Simulation'],0,15,['windows'],True,...,[],2,2,0,0.0,2 user reviews,100.0,0,False,2.99
71425,2294250,Speed Golf Royale,['Mainframe Games'],['Mainframe Games'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","['Action', 'Casual', 'Indie', 'Massively Multi...",0,0,['windows'],False,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.00
71426,2294160,Isle of Swaps,['Fuzz Force'],['Fuzz Force'],"['Single-player', 'Steam Achievements', 'Steam...","['Indie', 'RPG', 'Strategy']",0,29,['windows'],True,...,[],72,66,6,8.0,Very Positive,91.7,0,False,14.99
71427,2294130,Goobies,['Knifes'],['Knifes'],"['Single-player', 'Steam Achievements', 'Full ...","['Action', 'Casual', 'Indie', 'RPG', 'Strategy']",0,43,['windows'],True,...,[],1442,1312,130,8.0,Very Positive,91.0,0,False,5.99
71428,2294630,WindowBlinds 11,['Stardock'],['Stardock'],[],['Utilities'],0,0,['windows'],True,...,['WindowBlinds 11 - SkinStudio'],44,24,20,5.0,Mixed,54.5,0,False,29.99

In [10]:
df.set_index("steam_appid", inplace=True)

In [11]:
df.index

Index([2719580, 2719590, 2719600, 2719610, 2719650, 2719670, 2719680, 2719710,
       2719720, 2719740,
       ...
       2293680, 2293660, 2293530, 2294330, 2294320, 2294300, 2294250, 2294160,
       2294130, 2294630],
      dtype='int64', name='steam_appid', length=71429)

In [3]:
df.columns

Index(['steam_appid', 'name', 'developers', 'publishers', 'categories',
       'genres', 'required_age', 'n_achievements', 'platforms', 'is_released',
       'release_date', 'additional_content', 'total_reviews', 'total_positive',
       'total_negative', 'review_score', 'review_score_desc',
       'positive_percentual', 'metacritic', 'is_free', 'price_initial (USD)'],
      dtype='object')

In [4]:
# here I found the game with the steamapp id of 391540 (which is undertale)
df.loc[df['steam_appid'] == 391540]

,steam_appid,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,...,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
54794,391540,Undertale,['tobyfox'],['tobyfox'],"['Single-player', 'Steam Trading Cards', 'Remo...","['Indie', 'RPG']",92,0,"['windows', 'mac', 'linux']",True,...,['UNDERTALE Soundtrack'],127245,122812,4433,9.0,Overwhelmingly Positive,96.5,92,False,9.99

In [23]:
ut=df.loc[[391540,2719590]]
ut

,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,release_date,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
steam_appid,,,,,,,,,,,,,,,,,,,,
391540,Undertale,['tobyfox'],['tobyfox'],"['Single-player', 'Steam Trading Cards', 'Remo...","['Indie', 'RPG']",92,0,"['windows', 'mac', 'linux']",True,2015-09-15,['UNDERTALE Soundtrack'],127245,122812,4433,9.0,Overwhelmingly Positive,96.5,92,False,9.99
2719590,Light No Fire,['Hello Games'],['Hello Games'],"['Single-player', 'Multi-player', 'Co-op', 'On...","['Action', 'Adventure']",0,0,['windows'],False,NaT,[],0,0,0,0.0,No user reviews,0.0,0,False,0.00

In [37]:
games=df.loc[[391540,2719590], ['name','categories','platforms']]
games

,name,categories,platforms
steam_appid,,,
391540,Undertale,"['Single-player', 'Steam Trading Cards', 'Remo...","['windows', 'mac', 'linux']"
2719590,Light No Fire,"['Single-player', 'Multi-player', 'Co-op', 'On...",['windows']

In [39]:
g=games.explode('platforms')
g

# homework 2. second issue.  why is this not working

# explode is supposed to take a row in a dataframe and expands it into multiple rows on the column that you pick when that column is a list

# it should have put the game Undertale three times

,name,categories,platforms
steam_appid,,,
391540,Undertale,"['Single-player', 'Steam Trading Cards', 'Remo...","['windows', 'mac', 'linux']"
2719590,Light No Fire,"['Single-player', 'Multi-player', 'Co-op', 'On...",['windows']

In [19]:
e = pd.DataFrame({"key": "value"}, index=[1])
e

     key
1  value

In [20]:
e.index

Index([1], dtype='int64')

In [34]:
import numpy as np


#. making windows.  machine check it.  machine needs calibration.  it's looking for vibration.

# np.nan not a number
# np.empty

s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [29]:
# take the df dataframe and create a series

developers=df['developers']

In [33]:
developers

# homework 1. question.  what is developers?  it's a column name

# so why does this series s = pd.Series([1, 3, 5, np.nan, 6, 8])
# have the number '0' above it and the one developers=df['developers'] says 'developers'.  we know that a Pandas series has no columns.

# meaning you cannot write s.columns

steam_appid
2719580                   ['ぽけそう']
2719590            ['Hello Games']
2719600        ['GoldenGod Games']
2719610                ['Giammnn']
2719650            ['Saucy Melon']
                    ...
2294300    ['Super PowerUp Games']
2294250        ['Mainframe Games']
2294160             ['Fuzz Force']
2294130                 ['Knifes']
2294630               ['Stardock']
Name: developers, Length: 71429, dtype: object

In [ ]:
# how is rangeindex different than []

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71429 entries, 0 to 71428
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   steam_appid          71429 non-null  int64
 1   name                 71429 non-null  object
 2   developers           71429 non-null  object
 3   publishers           71429 non-null  object
 4   categories           71429 non-null  object
 5   genres               71429 non-null  object
 6   required_age         71429 non-null  int64
 7   n_achievements       71429 non-null  int64
 8   platforms            71429 non-null  object
 9   is_released          71429 non-null  bool
 10  release_date         71429 non-null  object
 11  additional_content   71429 non-null  object
 12  total_reviews        71429 non-null  int64
 13  total_positive       71429 non-null  int64
 14  total_negative       71429 non-null  int64
 15  review_score         71429 non-null  float64
 16  review_score_desc    71429 non-null  object
 17  positive_percentual  71429 non-null  float64
 18  metacritic           71429 non-null  int64
 19  is_free              71429 non-null  bool
 20  price_initial (USD)  71429 non-null  float64
dtypes: bool(2), float64(3), int64(7), object(9)
memory usage: 10.5+ MB

In [47]:
# we can see that the data type of 'release_date' column isn't the datetime object but instead just a numby object
df['release_date'] #.dtype

0                 2024-01-04
1               Not Released
2                 2024-01-26
3                 2024-02-17
4                 2024-01-05
                ...
71424    2024-02-09 00:00:00
71425           Not Released
71426    2024-09-27 00:00:00
71427    2023-07-14 00:00:00
71428    2023-02-15 00:00:00
Name: release_date, Length: 71429, dtype: object

In [42]:
# this isna() checks to see if something is not a number.  but I made mistake.
# a date is not a number.  np.Nat ?  means not a time
# df['release_date']


df['release_date'].isna()

steam_appid
2719580    False
2719590     True
2719600    False
2719610    False
2719650    False
           ...
2294300    False
2294250     True
2294160    False
2294130    False
2294630    False
Name: release_date, Length: 71429, dtype: bool

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71429 entries, 2719580 to 2294630
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 71429 non-null  object
 1   developers           71429 non-null  object
 2   publishers           71429 non-null  object
 3   categories           71429 non-null  object
 4   genres               71429 non-null  object
 5   required_age         71429 non-null  int64
 6   n_achievements       71429 non-null  int64
 7   platforms            71429 non-null  object
 8   is_released          71429 non-null  bool
 9   release_date         58041 non-null  datetime64[ns]
 10  additional_content   71429 non-null  object
 11  total_reviews        71429 non-null  int64
 12  total_positive       71429 non-null  int64
 13  total_negative       71429 non-null  int64
 14  review_score         71429 non-null  float64
 15  review_score_desc    71429 non-null  object
 16  positive_percentual  71429 non-null  float64
 17  metacritic           71429 non-null  int64
 18  is_free              71429 non-null  bool
 19  price_initial (USD)  71429 non-null  float64
dtypes: bool(2), datetime64[ns](1), float64(3), int64(6), object(8)
memory usage: 12.5+ MB

In [43]:
df.loc[2719590]

name                                                       Light No Fire
developers                                               ['Hello Games']
publishers                                               ['Hello Games']
categories             ['Single-player', 'Multi-player', 'Co-op', 'On...
genres                                           ['Action', 'Adventure']
required_age                                                           0
n_achievements                                                         0
platforms                                                    ['windows']
is_released                                                        False
release_date                                                         NaT
additional_content                                                    []
total_reviews                                                          0
total_positive                                                         0
total_negative                                                         0
review_score                                                         0.0
review_score_desc                                        No user reviews
positive_percentual                                                  0.0
metacritic                                                             0
is_free                                                            False
price_initial (USD)                                                  0.0
Name: 2719590, dtype: object

In [6]:
# therefore, it's convenient to convert it to the datetime before conducting any other manipulations
df['release_date'] = df['release_date'].str[:10] # we can slice every string value in the 'release_date' column so that every value that contains values like 2023-02-15 00:00:00 becomes just 2023-02-15
# I also tried iterating over it do the same this, but this caused an error due to a lot of df.insert calls

df['release_date'] = pd.to_datetime(df['release_date'], errors = 'coerce') # we then convert all values which are in the YYYY-MM-DD format to the datetime object
                                                                         # the errors = 'coerce' arg makes all the values that aren't in the YYYY-MM-DD format stay the same

['developers', 'publishers',    'genres' ,'required_age' ]

In [49]:
df['release_date'] = df['release_date'].str[:10]
df['release_date']

0        2024-01-04
1        Not Releas
2        2024-01-26
3        2024-02-17
4        2024-01-05
            ...
71424    2024-02-09
71425    Not Releas
71426    2024-09-27
71427    2023-07-14
71428    2023-02-15
Name: release_date, Length: 71429, dtype: object

In [50]:
df['release_date'] = pd.to_datetime(df['release_date'], errors = 'coerce')
df['release_date']

0       2024-01-04
1              NaT
2       2024-01-26
3       2024-02-17
4       2024-01-05
           ...
71424   2024-02-09
71425          NaT
71426   2024-09-27
71427   2023-07-14
71428   2023-02-15
Name: release_date, Length: 71429, dtype: datetime64[ns]

In [ ]:
# space
'20'
# null
'0'

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71429 entries, 0 to 71428
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   steam_appid          71429 non-null  int64
 1   name                 71429 non-null  object
 2   developers           71429 non-null  object
 3   publishers           71429 non-null  object
 4   categories           71429 non-null  object
 5   genres               71429 non-null  object
 6   required_age         71429 non-null  int64
 7   n_achievements       71429 non-null  int64
 8   platforms            71429 non-null  object
 9   is_released          71429 non-null  bool
 10  release_date         58041 non-null  datetime64[ns]
 11  additional_content   71429 non-null  object
 12  total_reviews        71429 non-null  int64
 13  total_positive       71429 non-null  int64
 14  total_negative       71429 non-null  int64
 15  review_score         71429 non-null  float64
 16  review_score_desc    71429 non-null  object
 17  positive_percentual  71429 non-null  float64
 18  metacritic           71429 non-null  int64
 19  is_free              71429 non-null  bool
 20  price_initial (USD)  71429 non-null  float64
dtypes: bool(2), datetime64[ns](1), float64(3), int64(7), object(8)
memory usage: 10.5+ MB

# Homework


* go to kaggle.com and download some data, preferable large. (make sure it has a date column somewhere)

* upload to github

* read into data frame using pandas

* print columns

* set index to something like and ID or date . you want it to be unique

* do a group by

* do a loc lookup by some logic


# Review this and if needed use this to clean you date column (or throw it away)


# how to handle dates

1.  we had data with 2024-01-04 for example.  we had data that said "not released"

2. so to filter out not released first he converted all the objects (which are strings) in df['release_date'] to a  datetime64[ns] using coerce which means if the date is not valid then set it to np.NaT. (not a timestamp)

3.  we made a dataset of only rows with valid date using .isna() like this.  there is no command to check for is np.NaT instead we have .isna() or .isnull() using this:

validDates = df.loc[df['release_date'].isna() == False, ['developers','publishers',    'genres' ,'required_age', 'release_date' ]  ]

4.  describe what this does:

- df.loc looks by index or by logical expression.  
- df['release_date'].isna() ==False looks at that series for valid dates
- df.loc[ some expression , column names]


## Extra Credit Homework

Investigagte homework 1 and homework 2

In [61]:




validDates = df.loc[df['release_date'].isna() == False, ['developers','publishers',    'genres' ,'required_age', 'release_date' ]  ]

validDates

,developers,publishers,genres,required_age,release_date
0,['ぽけそう'],['ぽけそう'],"['Casual', 'Indie']",0,2024-01-04
2,['GoldenGod Games'],['GoldenGod Games'],"['RPG', 'Strategy']",0,2024-01-26
3,['Giammnn'],['Giammnn'],"['Action', 'Casual', 'Indie', 'RPG']",0,2024-02-17
4,['Saucy Melon'],['Saucy Melon'],"['Action', 'Casual', 'Indie', 'Early Access']",0,2024-01-05
7,['Apericot Studio'],['Apericot Studio'],"['Action', 'Adventure', 'Indie', 'RPG', 'Simul...",0,2024-01-15
...,...,...,...,...,...
71423,"[""Cute Hannah's Games""]","[""Cute Hannah's Games""]","['Adventure', 'Casual', 'Indie', 'Simulation',...",0,2023-02-08
71424,['Super PowerUp Games'],['Super PowerUp Games'],['Simulation'],0,2024-02-09
71426,['Fuzz Force'],['Fuzz Force'],"['Indie', 'RPG', 'Strategy']",0,2024-09-27
71427,['Knifes'],['Knifes'],"['Action', 'Casual', 'Indie', 'RPG', 'Strategy']",0,2023-07-14
71428,['Stardock'],['Stardock'],['Utilities'],0,2023-02-15

In [7]:
df.loc[0,'release_date'].dtype

# you cannot see the dtype for the pandas Timestamp (which is practically the same as datetime in usual python).
                               # it returns an AttributeError, but we still can see that it's a Timestamp from the error info

AttributeError: 'Timestamp' object has no attribute 'dtype'

In [ ]:
# sorting the values by the release date
df.sort_values(by='release_date', ascending=False, inplace=True)
df['release_date']

In [ ]:
# setting the index to be the date
df.set_index(df['release_date'], inplace=True)
df

In [ ]:
# we can see the average price by platforms by using .groupby.mean
df.groupby('platforms')['price_initial (USD)'].mean()

In [ ]:
# locating the free games with 100% positive reviews
df['name'].loc[(df['is_free'] == True) & (df['positive_percentual'] == 100.0)]

In [ ]:
df.loc[df['name'] == 'Flappy Octane']